sam = User.create(username: "sbelkin", email: "sam@gmail.com", password_digest: "12345")
venue = Venue.create(name: "Martel", address: "Post Rd", city: "Fairfield", state: "CT", zip: "06825", phone: "203-222-2222", website: "www.martel.com")
experience = sam.experiences.build(venue: venue)
dish = experience.dishes.build(title: "pizza", review: "delicious cheese pizza")
dish2 = experience.dishes.build(title: "lo mein", review: "delicious")
